services:
  db:
    image: mysql:8.4
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3307:3306"  # optional: for local debugging

  backend:
    build:
      context: ./todo-backend
    container_name: todo-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      # CORS will read this (see CorsConfig change below)
      APP_ALLOWED_ORIGINS: http://localhost:3000
    healthcheck:
      test: ["CMD", "bash", "-lc", "exec 3<>/dev/tcp/127.0.0.1/8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./todo-frontend
      args:
        VITE_API_BASE_URL: /api
    container_name: todo-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"

volumes:
  mysql_data:
